apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: hub
  namespace: argocd
spec:
  description: "Project for management cluster apps"
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'
  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'