apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: cluster
    environment: sbox
    enable_metrics_server: "false"
    enable_cluster_autoscaler: "false"
    enable_gloo: "false"
    create_shared_project: "true"
    external_secrets: "true"
    external_dns: "false"
    gloo_gateway: "true"
    in_cluster: "true"
    addon/team-apps-repo: "true"
  annotations:
    k8s_cluster_name: k8s-docker-dekstop-secret
    addons_repo_url: https://github.com/ukatru/argocd-examples.git
    addons_repo_revision: HEAD
    argocd_project_name: hub
  name: k8s-docker-dekstop-secret
  namespace: argocd
type: Opaque
stringData:
  name: hub
  server: https://kubernetes.default.svc
data:
  config: ewogICJ0bHNDbGllbnRDb25maWciOiB7CiAgICAiaW5zZWN1cmUiOiBmYWxzZQogIH0KfQo=